CFLAGS += -mcmodel=kernel -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -mno-3dnow -mno-fma
CFLAGS += -fno-pie -m64
CPPFLAGS += -m64 -mcmodel=kernel -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -mno-3dnow -mno-fma

CFLAGS32 := -m32

CFLAGS16 := -march=i386 -mregparm=3 -fno-strict-aliasing -fomit-frame-pointer 
CFLAGS16 += -fno-pic -mno-mmx -mno-sse -fno-stack-protector
CFLAGS16 += -mpreferred-stack-boundary=2 -m16

LFLAGS +=  -z max-page-size=0x1000

LFLAGS16 :=  -z max-page-size=0x1000  -m elf_i386 --emit-relocs -T arch/x86_64/realmode/realmode.lds
