
srclist:= dynamic_cast.cc exception.cc guard.cc stdexcept.cc typeinfo.cc memory.cc auxhelper.cc libelftc_dem_gnu3.c
target := libcxxrt.obj
subdir :=

CFLAGS += -D_GNU_SOURCE
CXXFLAGS += -D_GNU_SOURCE

include $(TEMPLATEFILE)