
srclist:= dynamic_cast.cc \
		  guard.cc \
		  stdexcept.cc \
		  typeinfo.cc \
		  memory.cc \
		  auxhelper.cc \
		  libelftc_dem_gnu3.c \
		  cxa_atexit.c \
		  cxa_finalize.c \
		  # exception.cc \

subdir :=

CFLAGS += -D_GNU_SOURCE
CXXFLAGS += -D_GNU_SOURCE -fno-check-new

include $(TEMPLATEFILE)